steps:
  # Maven packaging
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['clean', 'package']
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/container-basic/hellorest-github', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/container-basic/hellorest-github']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'hellorest-github', '--image', 'asia.gcr.io/container-basic/hellorest-github', '--region', 'asia-northeast3', '--platform', 'managed', '--allow-unauthenticated']
images:
  - asia.gcr.io/container-basic/hellorest-github
